name: DevSecOps Pipeline
#triggers the workflow only on push or pull request events but only from the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  #allows to run the workflow manually from the Actions tab
  workflow_dispatch:

#workflow made of one or more jobs that can run sequentially or in parralel
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          path: "django.nv"
      - name: SECRET CHECK
        run: docker run --user $(id -u):$(id -g) -v "$(pwd):/src" --rm dxa4881/trufflehog file:///src -x /src/excluded.txt
        continue-on-error: true
      - name: CODE CHECK
        run: docker run --rm -e "WORKSPACE=${PWD}" -v "$PWD:/app:cached" quay.io/appthreat/sast-scan scan --src /app --type python
        continue-on-error: true
      - name: DEPENDENCY CHECK
        run: docker run --user $(id -u):$(id -g) -v $(pwd):/src --rm pyupio/safety safety check -r /src/requirements.txt --full-report
        continue-on-error: true    
  
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "django.nv"
      - name: App in docker
        run: |
          docker stop $(docker ps | grep 8000 | cut -d' ' -f1) || true
          docker build -t djangolocal django.nv
          docker run -p 8000:8000 -d djangolocal
#
          

  dast:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.5.0
        with: 
          target: 'http://localhost:8000'
          cmd_options: '-a -J reports/zapreport.json'








          


    
